import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Saladillo Vivo",
  description: "Generated by Gemini",
};

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
      </head>
      <body className="bg-main-gradient">
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
